import { TriggerSource } from '../types/index.js';

export type CommandName = 'review' | 'deep-review' | 'skip' | 'help';

export interface ParsedCommand {
  command: CommandName;
  /** Raw args after the command name. */
  args: string;
  /** The trigger source derived from the command. */
  trigger: TriggerSource;
}

const COMMAND_MAP: Record<string, CommandName> = {
  '/review': 'review',
  '/deep-review': 'deep-review',
  '/deep_review': 'deep-review',
  '/skip': 'skip',
  '/help': 'help',
};

const COMMAND_PATTERN = /^\/(review|deep-review|deep_review|skip|help)\b\s*(.*)$/im;

/**
 * Known bot accounts whose comments should be ignored (prevents self-trigger loops).
 */
const BOT_ACCOUNTS = new Set(['x-reviewer[bot]', 'dependabot[bot]', 'renovate[bot]']);

export interface CommandContext {
  commentBody: string;
  commentAuthor: string;
  prAuthor: string;
  /** Whether the commenter has write access to the repo (from GitHub event). */
  isCollaborator?: boolean;
}

/**
 * Parse slash commands from a GitHub comment body.
 * Returns null if no valid command found or if the commenter
 * is not authorized (non-collaborator trying /deep-review).
 */
export function parseCommand(ctx: CommandContext): ParsedCommand | null {
  if (BOT_ACCOUNTS.has(ctx.commentAuthor)) return null;

  const trimmed = ctx.commentBody.trim();
  const match = trimmed.match(COMMAND_PATTERN);
  if (!match) return null;

  const rawCmd = match[1].toLowerCase();
  const cmd = COMMAND_MAP[`/${rawCmd}`] ?? COMMAND_MAP[rawCmd];
  if (!cmd) return null;

  const args = (match[2] ?? '').trim();

  const trigger =
    cmd === 'deep-review' ? TriggerSource.Manual_Deep : TriggerSource.Manual_Review;

  return { command: cmd, args, trigger };
}

/**
 * Check whether a command is authorized for the commenter.
 * /deep-review requires collaborator access.
 * /skip restricted to PR author or collaborator.
 */
export function isAuthorized(ctx: CommandContext, cmd: ParsedCommand): boolean {
  // PR author can always trigger commands
  if (ctx.commentAuthor === ctx.prAuthor) return true;

  // Collaborators can trigger any command
  if (ctx.isCollaborator) return true;

  // Non-collaborators can only use /review and /help
  if (cmd.command === 'review' || cmd.command === 'help') return true;

  return false;
}

/**
 * Build a help text rendered when user types /help.
 */
export function buildHelpText(): string {
  return [
    '## 🤖 X-Reviewer 斜杠命令',
    '',
    '| 命令 | 触发方式 | 说明 |',
    '|------|----------|------|',
    '| `/review` | 任意用户 | 触发当前 PR 的全量 AI 代码评审 |',
    '| `/deep-review` | PR 作者 / Collaborator | 增强模式：加载完整文件上下文 + 安全规则扫描 |',
    '| `/skip` | PR 作者 / Collaborator | 跳过当前 PR 的评审（移除待处理队列） |',
    '| `/help` | 任意用户 | 显示此帮助信息 |',
    '',
    '> 注意：X-Reviewer 仅在 PR 中生效，Issue 中的命令会被忽略。',
    '',
    '---',
    '<sub>🤖 Generated by [X-Reviewer](https://github.com/magicman1324/X-Reviewer)</sub>',
  ].join('\n');
}
